import { objectType, extendType, arg, floatArg, stringArg, nonNull, intArg } from 'nexus'
import { requireAuthenticatedUser } from './__authhelper'

export const Room = objectType({
    name: 'Room',
    sourceType: 'RoomModel',
    definition(t) {
        t.int('roomId'),
        t.int('locationId'),
        t.string('name'),
        t.field('created_by', {
            type: 'User',
            resolve(roomModel, _, ctx) {
                return ctx.db.roomDAO.getUser(roomModel.roomId)
            }
        }),
        t.datetime('created_at')
    },
})

export const RoomQuery = extendType({
    type: 'Query',
    definition(t) {
        t.list.field('rooms', {
            type: 'Room',
            args: { roomId: intArg() },
            async resolve(_root, _args, ctx) {
                if (_args == null || _args.roomId == null) {
                return ctx.db.roomDAO.getMany();
            }
                if (_args != null && _args.roomId != null) {
                    const single = await ctx.db.roomDAO.getById(_args.roomId);
                    return [ single ] ;
                }
                return null;
            }
        })
    },
})

export const RoomMutation = extendType({
    type: 'Mutation',
    definition(t) {
        t.field('createRoom', {
            type: 'Room',
            args: {
                name: nonNull(stringArg()),
                locationId: nonNull(intArg()),
            },
            async resolve(_root, args, ctx) {
                const authenticatedUser = await ctx.authHelper.getAuthenticatedUser()
                const room  = {
                    name: args.name,
                    locationId: args.locationId,
                    created_id: authenticatedUser.id
                }
                //@ts-ignore: missing ID is okay, as it will be autogenerated
                //TODO: perhaps create a NewRoom type with no ID
                const newRoom = await ctx.db.roomDAO.create( room )
                return newRoom
            }
        })
    }
})